name: Build and Check

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --release

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
